import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Script from "next/script";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Job board App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        {/* For modern browsers with module support */}
        <Script
          src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.esm.js"
          strategy="afterInteractive"
          type="module"
        />

        {/* For older browsers without module support */}
        <Script
          src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.js"
          strategy="afterInteractive"
          noModule
        />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
// import Script from "next/script";

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <head>
//         {/* For modern browsers with module support */}
//         <Script
//           src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.esm.js"
//           strategy="afterInteractive"
//           type="module"
//         />

//         {/* For older browsers without module support */}
//         <Script
//           src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.js"
//           strategy="afterInteractive"
//           noModule
//         />
//       </head>
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         {children}
//       </body>
//     </html>
//   );
// }
